name: NodeJS with Gulp

on:
  push:
    branches: [ "main" , "redo"]
  pull_request:
    branches: [ "main" , "redo"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
     # Installs all dependecies of Project   
    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        npm install
        gulp
