name: NodeJS Building

on:
  push:
    branches: [ "main", "redo" ]
  pull_request:
    branches: [ "main", "redo" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Install all dependencies
    - name: Install dependencies
      run: npm install
      working-directory: ./server

    - name: Force Fix Vulnerabilities
      run: npm audit fix --force || true
      working-directory: ./server
      
    - name: Show secrets
      run: echo ${{ secrets.MONGO_URL }}
      
    # Run ESLint with the specified configuration file
    - name: Run ESLint
      run: npx eslint -c ./server/eslint.config.mjs
      working-directory: ./server

